version: '3'
services:
  backend:
    build: 
      dockerfile: ./backend/Dockerfile 
      context: ./backend
    env_file:
      - .env
    expose:
      - 80
    links:
      - database
  frontend:
    build: 
      dockerfile: ./frontend/Dockerfile 
      context: ./frontend
    ports:
      - 80:80
    links:
      - backend
  database:
    image: postgres:10.5-alpine
    restart: always
    env_file:
      - .env
    expose:
      - 5432